(()=>{
/* Nudeps v0.2.4 */
let cS = document.currentScript;
let mapUrl = cS?.src;
let map = {
	"imports": {
		"open-props": "./client_modules/open-props@1.7.23/dist/open-props.module.js",
		"open-props/animations": "./client_modules/open-props@1.7.23/animations.min.css",
		"open-props/aspects": "./client_modules/open-props@1.7.23/aspects.min.css",
		"open-props/blue": "./client_modules/open-props@1.7.23/blue.min.css",
		"open-props/blue-hsl": "./client_modules/open-props@1.7.23/blue-hsl.min.css",
		"open-props/borders": "./client_modules/open-props@1.7.23/borders.min.css",
		"open-props/brand-colors": "./client_modules/open-props@1.7.23/brand-colors.min.css",
		"open-props/brown": "./client_modules/open-props@1.7.23/brown.min.css",
		"open-props/brown-hsl": "./client_modules/open-props@1.7.23/brown-hsl.min.css",
		"open-props/buttons": "./client_modules/open-props@1.7.23/buttons.min.css",
		"open-props/buttons/dark": "./client_modules/open-props@1.7.23/buttons.dark.min.css",
		"open-props/buttons/light": "./client_modules/open-props@1.7.23/buttons.light.min.css",
		"open-props/camo": "./client_modules/open-props@1.7.23/camo.min.css",
		"open-props/camo-hsl": "./client_modules/open-props@1.7.23/camo-hsl.min.css",
		"open-props/choco": "./client_modules/open-props@1.7.23/choco.min.css",
		"open-props/choco-hsl": "./client_modules/open-props@1.7.23/choco-hsl.min.css",
		"open-props/colors": "./client_modules/open-props@1.7.23/colors.min.css",
		"open-props/colors-hd": "./client_modules/open-props@1.7.23/colors-oklch.min.css",
		"open-props/colors-hsl": "./client_modules/open-props@1.7.23/colors-hsl.min.css",
		"open-props/cyan": "./client_modules/open-props@1.7.23/cyan.min.css",
		"open-props/cyan-hsl": "./client_modules/open-props@1.7.23/cyan-hsl.min.css",
		"open-props/design-tokens": "./client_modules/open-props@1.7.23/open-props.tokens.json",
		"open-props/durations": "./client_modules/open-props@1.7.23/durations.min.css",
		"open-props/easings": "./client_modules/open-props@1.7.23/easings.min.css",
		"open-props/fonts": "./client_modules/open-props@1.7.23/fonts.min.css",
		"open-props/gradients": "./client_modules/open-props@1.7.23/gradients.min.css",
		"open-props/gray": "./client_modules/open-props@1.7.23/gray.min.css",
		"open-props/gray-hd": "./client_modules/open-props@1.7.23/gray-oklch.min.css",
		"open-props/gray-hsl": "./client_modules/open-props@1.7.23/gray-hsl.min.css",
		"open-props/green": "./client_modules/open-props@1.7.23/green.min.css",
		"open-props/green-hsl": "./client_modules/open-props@1.7.23/green-hsl.min.css",
		"open-props/indigo": "./client_modules/open-props@1.7.23/indigo.min.css",
		"open-props/indigo-hsl": "./client_modules/open-props@1.7.23/indigo-hsl.min.css",
		"open-props/jungle": "./client_modules/open-props@1.7.23/jungle.min.css",
		"open-props/jungle-hsl": "./client_modules/open-props@1.7.23/jungle-hsl.min.css",
		"open-props/lime": "./client_modules/open-props@1.7.23/lime.min.css",
		"open-props/lime-hsl": "./client_modules/open-props@1.7.23/lime-hsl.min.css",
		"open-props/masks/corner-cuts": "./client_modules/open-props@1.7.23/masks.corner-cuts.min.css",
		"open-props/masks/edges": "./client_modules/open-props@1.7.23/masks.edges.min.css",
		"open-props/media": "./client_modules/open-props@1.7.23/media.min.css",
		"open-props/normalize": "./client_modules/open-props@1.7.23/normalize.min.css",
		"open-props/normalize/dark": "./client_modules/open-props@1.7.23/normalize.dark.min.css",
		"open-props/normalize/light": "./client_modules/open-props@1.7.23/normalize.light.min.css",
		"open-props/oklch-hues": "./client_modules/open-props@1.7.23/oklch-hues.min.css",
		"open-props/orange": "./client_modules/open-props@1.7.23/orange.min.css",
		"open-props/orange-hsl": "./client_modules/open-props@1.7.23/orange-hsl.min.css",
		"open-props/palette": "./client_modules/open-props@1.7.23/palette.min.css",
		"open-props/pink": "./client_modules/open-props@1.7.23/pink.min.css",
		"open-props/pink-hsl": "./client_modules/open-props@1.7.23/pink-hsl.min.css",
		"open-props/postcss/brand": "./client_modules/open-props@1.7.23/src/extra/brand.css",
		"open-props/postcss/buttons": "./client_modules/open-props@1.7.23/src/extra/buttons.css",
		"open-props/postcss/buttons/dark": "./client_modules/open-props@1.7.23/src/extra/buttons.dark.css",
		"open-props/postcss/buttons/light": "./client_modules/open-props@1.7.23/src/extra/buttons.light.css",
		"open-props/postcss/normalize": "./client_modules/open-props@1.7.23/src/extra/normalize.css",
		"open-props/postcss/normalize/dark": "./client_modules/open-props@1.7.23/src/extra/normalize.dark.css",
		"open-props/postcss/normalize/light": "./client_modules/open-props@1.7.23/src/extra/normalize.light.css",
		"open-props/postcss/shadows/dark": "./client_modules/open-props@1.7.23/src/props.shadows.dark.css",
		"open-props/postcss/shadows/light": "./client_modules/open-props@1.7.23/src/props.shadows.light.css",
		"open-props/postcss/style": "./client_modules/open-props@1.7.23/src/index.css",
		"open-props/postcss/theme": "./client_modules/open-props@1.7.23/src/extra/theme.css",
		"open-props/purple": "./client_modules/open-props@1.7.23/purple.min.css",
		"open-props/purple-hsl": "./client_modules/open-props@1.7.23/purple-hsl.min.css",
		"open-props/red": "./client_modules/open-props@1.7.23/red.min.css",
		"open-props/red-hsl": "./client_modules/open-props@1.7.23/red-hsl.min.css",
		"open-props/resolver": "./client_modules/open-props@1.7.23/open-props.resolver.json",
		"open-props/sand": "./client_modules/open-props@1.7.23/sand.min.css",
		"open-props/sand-hsl": "./client_modules/open-props@1.7.23/sand-hsl.min.css",
		"open-props/shadow/animations": "./client_modules/open-props@1.7.23/animations.shadow.min.css",
		"open-props/shadow/aspects": "./client_modules/open-props@1.7.23/aspects.shadow.min.css",
		"open-props/shadow/blue": "./client_modules/open-props@1.7.23/blue.shadow.min.css",
		"open-props/shadow/blue-hsl": "./client_modules/open-props@1.7.23/blue-hsl.shadow.min.css",
		"open-props/shadow/borders": "./client_modules/open-props@1.7.23/borders.shadow.min.css",
		"open-props/shadow/brown": "./client_modules/open-props@1.7.23/brown.shadow.min.css",
		"open-props/shadow/brown-hsl": "./client_modules/open-props@1.7.23/brown-hsl.shadow.min.css",
		"open-props/shadow/camo": "./client_modules/open-props@1.7.23/camo.shadow.min.css",
		"open-props/shadow/camo-hsl": "./client_modules/open-props@1.7.23/camo-hsl.shadow.min.css",
		"open-props/shadow/choco": "./client_modules/open-props@1.7.23/choco.shadow.min.css",
		"open-props/shadow/choco-hsl": "./client_modules/open-props@1.7.23/choco-hsl.shadow.min.css",
		"open-props/shadow/colors": "./client_modules/open-props@1.7.23/colors.shadow.min.css",
		"open-props/shadow/colors-hsl": "./client_modules/open-props@1.7.23/colors-hsl.shadow.min.css",
		"open-props/shadow/cyan": "./client_modules/open-props@1.7.23/cyan.shadow.min.css",
		"open-props/shadow/cyan-hsl": "./client_modules/open-props@1.7.23/cyan-hsl.shadow.min.css",
		"open-props/shadow/easings": "./client_modules/open-props@1.7.23/easings.shadow.min.css",
		"open-props/shadow/fonts": "./client_modules/open-props@1.7.23/fonts.shadow.min.css",
		"open-props/shadow/gradients": "./client_modules/open-props@1.7.23/gradients.shadow.min.css",
		"open-props/shadow/gray": "./client_modules/open-props@1.7.23/gray.shadow.min.css",
		"open-props/shadow/gray-hsl": "./client_modules/open-props@1.7.23/gray-hsl.shadow.min.css",
		"open-props/shadow/green": "./client_modules/open-props@1.7.23/green.shadow.min.css",
		"open-props/shadow/green-hsl": "./client_modules/open-props@1.7.23/green-hsl.shadow.min.css",
		"open-props/shadow/indigo": "./client_modules/open-props@1.7.23/indigo.shadow.min.css",
		"open-props/shadow/indigo-hsl": "./client_modules/open-props@1.7.23/indigo-hsl.shadow.min.css",
		"open-props/shadow/jungle": "./client_modules/open-props@1.7.23/jungle.shadow.min.css",
		"open-props/shadow/jungle-hsl": "./client_modules/open-props@1.7.23/jungle-hsl.shadow.min.css",
		"open-props/shadow/lime": "./client_modules/open-props@1.7.23/lime.shadow.min.css",
		"open-props/shadow/lime-hsl": "./client_modules/open-props@1.7.23/lime-hsl.shadow.min.css",
		"open-props/shadow/normalize": "./client_modules/open-props@1.7.23/normalize.shadow.min.css",
		"open-props/shadow/orange": "./client_modules/open-props@1.7.23/orange.shadow.min.css",
		"open-props/shadow/orange-hsl": "./client_modules/open-props@1.7.23/orange-hsl.shadow.min.css",
		"open-props/shadow/pink": "./client_modules/open-props@1.7.23/pink.shadow.min.css",
		"open-props/shadow/pink-hsl": "./client_modules/open-props@1.7.23/pink-hsl.shadow.min.css",
		"open-props/shadow/purple": "./client_modules/open-props@1.7.23/purple.shadow.min.css",
		"open-props/shadow/purple-hsl": "./client_modules/open-props@1.7.23/purple-hsl.shadow.min.css",
		"open-props/shadow/red": "./client_modules/open-props@1.7.23/red.shadow.min.css",
		"open-props/shadow/red-hsl": "./client_modules/open-props@1.7.23/red-hsl.shadow.min.css",
		"open-props/shadow/sand": "./client_modules/open-props@1.7.23/sand.shadow.min.css",
		"open-props/shadow/sand-hsl": "./client_modules/open-props@1.7.23/sand-hsl.shadow.min.css",
		"open-props/shadow/shadows": "./client_modules/open-props@1.7.23/shadows.shadow.min.css",
		"open-props/shadow/sizes": "./client_modules/open-props@1.7.23/sizes.shadow.min.css",
		"open-props/shadow/stone": "./client_modules/open-props@1.7.23/stone.shadow.min.css",
		"open-props/shadow/stone-hsl": "./client_modules/open-props@1.7.23/stone-hsl.shadow.min.css",
		"open-props/shadow/style": "./client_modules/open-props@1.7.23/open-props.shadow.min.css",
		"open-props/shadow/teal": "./client_modules/open-props@1.7.23/teal.shadow.min.css",
		"open-props/shadow/teal-hsl": "./client_modules/open-props@1.7.23/teal-hsl.shadow.min.css",
		"open-props/shadow/violet": "./client_modules/open-props@1.7.23/violet.shadow.min.css",
		"open-props/shadow/violet-hsl": "./client_modules/open-props@1.7.23/violet-hsl.shadow.min.css",
		"open-props/shadow/yellow": "./client_modules/open-props@1.7.23/yellow.shadow.min.css",
		"open-props/shadow/yellow-hsl": "./client_modules/open-props@1.7.23/yellow-hsl.shadow.min.css",
		"open-props/shadow/zindex": "./client_modules/open-props@1.7.23/zindex.shadow.min.css",
		"open-props/shadows": "./client_modules/open-props@1.7.23/shadows.min.css",
		"open-props/shadows/dark": "./client_modules/open-props@1.7.23/shadows.dark.min.css",
		"open-props/shadows/light": "./client_modules/open-props@1.7.23/shadows.light.min.css",
		"open-props/sizes": "./client_modules/open-props@1.7.23/sizes.min.css",
		"open-props/src": "./client_modules/open-props@1.7.23/src/index.js",
		"open-props/src/animations": "./client_modules/open-props@1.7.23/src/props.animations.js",
		"open-props/src/aspects": "./client_modules/open-props@1.7.23/src/props.aspects.js",
		"open-props/src/borders": "./client_modules/open-props@1.7.23/src/props.borders.js",
		"open-props/src/brand-colors": "./client_modules/open-props@1.7.23/src/props.brand-colors.js",
		"open-props/src/colors": "./client_modules/open-props@1.7.23/src/props.colors.js",
		"open-props/src/colors-hsl": "./client_modules/open-props@1.7.23/src/props.colors-hsl.js",
		"open-props/src/easing": "./client_modules/open-props@1.7.23/src/props.easing.js",
		"open-props/src/fonts": "./client_modules/open-props@1.7.23/src/props.fonts.js",
		"open-props/src/gradients": "./client_modules/open-props@1.7.23/src/props.gradients.js",
		"open-props/src/masks.corner-cuts": "./client_modules/open-props@1.7.23/src/props.masks.corner-cuts.js",
		"open-props/src/masks.edges": "./client_modules/open-props@1.7.23/src/props.masks.edges.js",
		"open-props/src/media": "./client_modules/open-props@1.7.23/src/props.media.js",
		"open-props/src/palette": "./client_modules/open-props@1.7.23/src/props.palette.js",
		"open-props/src/shadows": "./client_modules/open-props@1.7.23/src/props.shadows.js",
		"open-props/src/sizes": "./client_modules/open-props@1.7.23/src/props.sizes.js",
		"open-props/src/svg": "./client_modules/open-props@1.7.23/src/props.svg.js",
		"open-props/src/zindex": "./client_modules/open-props@1.7.23/src/props.zindex.js",
		"open-props/stone": "./client_modules/open-props@1.7.23/stone.min.css",
		"open-props/stone-hsl": "./client_modules/open-props@1.7.23/stone-hsl.min.css",
		"open-props/style": "./client_modules/open-props@1.7.23/open-props.min.css",
		"open-props/style-dictionary-tokens": "./client_modules/open-props@1.7.23/open-props.style-dictionary-tokens.json",
		"open-props/switch/dark": "./client_modules/open-props@1.7.23/theme.dark.switch.min.css",
		"open-props/switch/light": "./client_modules/open-props@1.7.23/theme.light.switch.min.css",
		"open-props/teal": "./client_modules/open-props@1.7.23/teal.min.css",
		"open-props/teal-hsl": "./client_modules/open-props@1.7.23/teal-hsl.min.css",
		"open-props/tokens": "./client_modules/open-props@1.7.23/open-props.tokens.json",
		"open-props/utilities": "./client_modules/open-props@1.7.23/src/extra/utilities.css",
		"open-props/violet": "./client_modules/open-props@1.7.23/violet.min.css",
		"open-props/violet-hsl": "./client_modules/open-props@1.7.23/violet-hsl.min.css",
		"open-props/yellow": "./client_modules/open-props@1.7.23/yellow.min.css",
		"open-props/yellow-hsl": "./client_modules/open-props@1.7.23/yellow-hsl.min.css",
		"open-props/zindex": "./client_modules/open-props@1.7.23/zindex.min.css",
		"open-props/": "./client_modules/open-props@1.7.23/"
	}
};
if (!mapUrl && !cS) {
	throw new Error('nudeps: Import map script appears to be loaded as a module. Set module: true in nudeps config, or remove type="module" from the script tag.');
}
if (document.querySelector("script[type=module]")) {
	console.warn("nudeps: " + cS.getAttribute("src") + " is included after module scripts, which is not supported in all browsers.");
}
const rebase = m => { for (let k in m) m[k] = new URL(m[k], mapUrl).href; return m; };
rebase(map.imports);
for (let scope in map.scopes) rebase(map.scopes[scope]);
let script = Object.assign(document.createElement("script"), { type: "importmap", textContent: JSON.stringify(map) });
if (cS) cS.after(script);
else (document.head ?? document.documentElement).append(script);
})();